name: Build, publish, and deploy frontend Docker image to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: |
          docker build -t frontendapp .

      - name: Tag Docker image
        run: |
          docker tag frontendapp:latest 654654282708.dkr.ecr.ap-southeast-1.amazonaws.com/safal-frontend:latest

      - name: Push Docker image to Amazon ECR
        run: |
          docker push 654654282708.dkr.ecr.ap-southeast-1.amazonaws.com/safal-frontend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build  # This ensures the deploy job runs after the build job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy code to EC2
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            aws ecr get-login-password --region ap-southeast-1 | sudo docker login --username AWS --password-stdin 654654282708.dkr.ecr.ap-southeast-1.amazonaws.com
            sudo docker pull 654654282708.dkr.ecr.ap-southeast-1.amazonaws.com/safal-frontend:latest
            sudo docker stop frontend || true
            sudo docker rm frontend || true
            sudo docker run -d --name frontend -p 3000:80 654654282708.dkr.ecr.ap-southeast-1.amazonaws.com/safal-frontend:latest
